### ISSUE TITLE
Convert into VCC package

### ISSUE THREAD

**Issue by Happyrobot33** [z3y/ClusteredBIRP#1]
I think it would be beneficial for this to become a VCC package so its easy to install into new worlds, alongside being able to keep the files for this system out of the assets folder

**Comment by Happyrobot33** [comment]
Just realized it is technically in the right format, just it isnt live yet on any VCC repos from what I can tell

**Comment by z3y** [comment]
making vcc packages can be a bit annoying so i havent done that, and its still experimental and for people who are more techical so i dont consider vcc is needed yet
